apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dev
type: Opaque
stringData:
  DATABASE_USER: "dev_user"
  DATABASE_PASSWORD: "dev_password_123"
  JWT_SECRET: "dev_jwt_secret_key_change_in_production"
  API_KEY: "dev_api_key_12345"
  ENCRYPTION_KEY: "dev_encryption_key_32_chars_min"